### ISSUE TITLE
[paid] $200 Research database implementation 

### ISSUE THREAD

**Issue by aweb3dad** [The-Web3-Family/democracy-mobile-app-backend#1]
(ai generated, let's slowly figure out how to make sure the resolution is communicated well)

# Database Design: Congress.gov Integration

## Overview
This document outlines the steps and requirements for implementing a database to store data retrieved from the Congress.gov API. The main focus is on modeling data entities provided by the API and ensuring the database is structured to handle all relevant entities efficiently.

---

## Key Requirements

1. **UML Modeling**
   - Create a UML diagram to model the relationships between entities derived from the Congress.gov API.
   - Include all relevant attributes and relationships for each entity.

2. **Entity Tables**
   - Generate a table for **every entity** provided by the Congress.gov API.
   - Each table will:
     - Be prefixed with `congress.gov_` to distinguish them.
     - Align with the structure of the corresponding entity from the API.

3. **Data Sources**
   - The data will be pulled directly from the Congress.gov API.
   - Tables will represent entities such as:
     - Bills
     - Legislators
     - Committees
     - Votes
     - Amendments
     - Congressional Records, etc.

4. **Scalability**
   - Prepare the database for `n` number of tables, where `n` equals the total number of unique entities in the API.
   - Ensure relationships between entities are normalized to avoid redundancy.

5. **Naming Conventions**
   - Use clear and consistent prefixes:
     - Example: `congress.gov_bills`, `congress.gov_legislators`.
   - Maintain camelCase or snake_case formatting throughout.

---

## Cloud Hosting Requirements

1. **Cloud SQL Instance**
   - Use a cloud-hosted MySQL database to store the data.
   - Current consideration is AWS, but alternatives may be explored due to:
     - Complexity and potential hidden fees in AWS.
     - Preference for a free or lower-cost SaaS solution.
     - Justification for client-related costs.

2. **Platform Evaluation**
   - Evaluate cloud platforms for ease of use, cost-efficiency, and scalability.
   - Preferred options may include platforms like Google Cloud SQL, Azure, or other SaaS database services.

3. **Cost Sensitivity**
   - Minimize hosting costs, ensuring expenses align with client expectations.
   - Look for free-tier options or platforms with predictable, low fees.

---

## Cron Job Requirements (Definition of GUN)

1. **Purpose**
   - A cron job will automate the process of pulling data from the Congress.gov API and populating the database.

2. **Minimum Viable Functionality**
   - The cron job must:
     - Fetch data from Congress.gov API at regular intervals.
     - Populate the cloud-hosted SQL database with fetched data.
     - Ensure all entities are synced correctly with their respective tables.

3. **Implementation Details**
   - Schedule: Define the frequency (e.g., hourly, daily).
   - Error Handling: Log and handle errors during API calls or database updates.
   - Monitoring: Ensure the cron job is operational and data integrity is maintained.

4. **Outcome**
   - The database must consistently receive and store up-to-date data from Congress.gov via the cron job.
   - This functionality represents the **minimum definition of GUN** for project deliverables.

---

## Next Steps
1. Draft UML diagram for database structure.
2. Evaluate and select a cloud SQL hosting provider.
3. Implement and test the cron job for API data synchronization.
4. Begin populating the database to meet the definition of GUN.

**Comment by aweb3dad** [comment]
@GideonMoses11 fyi this is the data model so far (not the database with the prefixed congressgov_x) : https://my.api.mockaroo.com/bills.json?key=c83ad9c0

That's what the ux coder will be using to display bills, I'll explain all that soon, gathering us in a slack channel soon

**Comment by GideonMoses11** [comment]
1. UML MODELING: I don't have enough information about the entities we'll be working with for now so this will wait

**Comment by GideonMoses11** [comment]
2. TABLES: For the tables, I've seen that we will have more tables but we need to specify the exact attributes we will extract. I don't think using the congress.gov prefix is necessary for the tables because we won't be using another project in that same database so sticking to bills_table, users_table etc is fine, they're distinct already

**Comment by GideonMoses11** [comment]
3. ENTITY RELATIONSHIP: Bills, Legislators, Committees, Votes, Amendments, Congressional Records, etc. We need to know all the needed attributes for these entities and if that is done we can then easily set the relationship between the necessary tables as needed

**Comment by GideonMoses11** [comment]
4. CLOUD HOSTING: For the Server, AWS is good but its expensive though it depends on budget. There are other budget friendly platforms like digital ocean, scalaway, linode, hetzner, vultr etc, the database (mySQL or Postgres) will also be on the server. The listed platforms are scalable, cost-effective, easy to use and efficient.

**Comment by GideonMoses11** [comment]
5. CRON: For this cron, once the database structure and entity attributes to be required are specified, setting it up won't be much of a headache. A backend function will be written to crawl and fetch data then store in our database according to the schedule and frequency we set.

**Comment by GideonMoses11** [comment]
6. ERROR HANDLING: For this, even after catching all errors via our code structure, we can also setup sentry so that we can see and trace errors visually  and as well trace any unknown inadequacy or malfunctioningin the system

**Comment by aweb3dad** [comment]
Completed, working on it with the other PR
